---
abstract: 'Various simple setup routines for testing'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Setup-Test
requires:
  Log::Any: 0
  Rinci: 1.1.0
  Test::More: 0.96
  Test::Setup: 0.13
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Setup-Test/
  repository: http://github.com/sharyanto/perl-Setup-Test
version: 0.06
